<Project>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <SufiVersion>0.0.0-alpha.1.0</SufiVersion>
        <AbpVersion>10.3.0</AbpVersion>
        <MicrosoftAspNetCoreComponentsWebVersion>10.0.2</MicrosoftAspNetCoreComponentsWebVersion>
        <MicrosoftExtensionsLocalizationVersion>10.0.2</MicrosoftExtensionsLocalizationVersion>
        <MicrosoftExtensionsFileProvidersEmbeddedVersion>10.0.2</MicrosoftExtensionsFileProvidersEmbeddedVersion>
    </PropertyGroup>

    <PropertyGroup>
        <ConfigureAwaitFodyVersion>3.3.1</ConfigureAwaitFodyVersion>
        <FodyVersion>6.5.3</FodyVersion>
    </PropertyGroup>

</Project>
