<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AbpVersion>10.6.1</AbpVersion>
    <AspNetCoreVersion>10.0.9</AspNetCoreVersion>
    <MicrosoftAspNetCoreComponentsWebVersion>10.0.9</MicrosoftAspNetCoreComponentsWebVersion>
    <MicrosoftExtensionsLocalizationVersion>10.0.9</MicrosoftExtensionsLocalizationVersion>
    <MicrosoftExtensionsFileProvidersEmbeddedVersion>10.0.9</MicrosoftExtensionsFileProvidersEmbeddedVersion>
  </PropertyGroup>

</Project>
