// Auto-generated from .cursor/plans/icons-list.csv - do not edit by hand
namespace SufiChain.SufiBlazor.Icons;

internal static partial class SufiIconsGenerated
{
    public static (string name, SiIconCategory category, string description)[] CsvIcons { get; } =
    [
        ("chevron-down", SiIconCategory.Navigation, "Downward chevron indicator"),
        ("chevron-up", SiIconCategory.Navigation, "Upward chevron indicator"),
        ("chevron-left", SiIconCategory.Navigation, "Left chevron indicator"),
        ("chevron-right", SiIconCategory.Navigation, "Right chevron indicator"),
        ("arrow-up", SiIconCategory.Navigation, "Arrow pointing up"),
        ("arrow-down", SiIconCategory.Navigation, "Arrow pointing down"),
        ("arrow-left", SiIconCategory.Navigation, "Arrow pointing left"),
        ("arrow-right", SiIconCategory.Navigation, "Arrow pointing right"),
        ("home", SiIconCategory.Navigation, "Home or dashboard"),
        ("menu", SiIconCategory.Navigation, "Main menu hamburger"),
        ("plus", SiIconCategory.Actions, "Add or create action"),
        ("minus", SiIconCategory.Actions, "Remove or subtract action"),
        ("x", SiIconCategory.Actions, "Close or cancel"),
        ("check", SiIconCategory.Actions, "Confirm or success"),
        ("refresh", SiIconCategory.Actions, "Reload or sync"),
        ("search", SiIconCategory.Actions, "Search or find"),
        ("edit", SiIconCategory.Actions, "Edit or modify"),
        ("trash", SiIconCategory.Actions, "Delete item"),
        ("copy", SiIconCategory.Actions, "Duplicate or copy"),
        ("save", SiIconCategory.Actions, "Save changes"),
        ("upload", SiIconCategory.Media, "Upload content"),
        ("download", SiIconCategory.Media, "Download content"),
        ("image", SiIconCategory.Media, "Single image"),
        ("images", SiIconCategory.Media, "Image gallery"),
        ("video", SiIconCategory.Media, "Video or media player"),
        ("music", SiIconCategory.Media, "Music or audio"),
        ("microphone", SiIconCategory.Media, "Voice input or recording"),
        ("camera", SiIconCategory.Media, "Camera or capture"),
        ("play", SiIconCategory.Media, "Play action"),
        ("pause", SiIconCategory.Media, "Pause action"),
        ("file", SiIconCategory.Files, "Generic file"),
        ("file-text", SiIconCategory.Files, "Text document"),
        ("file-pdf", SiIconCategory.Files, "PDF document"),
        ("folder", SiIconCategory.Files, "Folder closed"),
        ("folder-open", SiIconCategory.Files, "Folder open"),
        ("cloud", SiIconCategory.Files, "Cloud storage"),
        ("user", SiIconCategory.Users, "Single user"),
        ("users", SiIconCategory.Users, "Multiple users"),
        ("user-plus", SiIconCategory.Users, "Add user"),
        ("user-minus", SiIconCategory.Users, "Remove user"),
        ("id-card", SiIconCategory.Users, "User identity"),
        ("contact", SiIconCategory.Users, "Contact or address book entry"),
        ("lock", SiIconCategory.Security, "Locked or secure"),
        ("unlock", SiIconCategory.Security, "Unlocked state"),
        ("shield", SiIconCategory.Security, "Protection or security"),
        ("key", SiIconCategory.Security, "Access key"),
        ("eye", SiIconCategory.Security, "Visible state"),
        ("eye-off", SiIconCategory.Security, "Hidden state"),
        ("settings", SiIconCategory.System, "Settings or configuration"),
        ("sliders", SiIconCategory.System, "Adjust controls"),
        ("bell", SiIconCategory.System, "Notifications"),
        ("info", SiIconCategory.System, "Information"),
        ("warning", SiIconCategory.System, "Warning alert"),
        ("error", SiIconCategory.System, "Error state"),
        ("chart-bar", SiIconCategory.Charts, "Bar chart"),
        ("chart-line", SiIconCategory.Charts, "Line chart"),
        ("chart-pie", SiIconCategory.Charts, "Pie chart"),
        ("trend-up", SiIconCategory.Charts, "Upward trend"),
        ("trend-down", SiIconCategory.Charts, "Downward trend"),
        ("calendar", SiIconCategory.Time, "Calendar date"),
        ("clock", SiIconCategory.Time, "Time or duration"),
        ("timer", SiIconCategory.Time, "Timer or countdown"),
        ("mail", SiIconCategory.Communication, "Email message"),
        ("chat", SiIconCategory.Communication, "Chat or message"),
        ("send", SiIconCategory.Communication, "Send message"),
        ("phone", SiIconCategory.Communication, "Phone call"),
        ("map", SiIconCategory.Location, "Map or location"),
        ("pin", SiIconCategory.Location, "Location pin"),
        ("globe", SiIconCategory.Location, "Global or world"),
        ("building", SiIconCategory.Location, "Building or office"),
        ("truck", SiIconCategory.Logistics, "Delivery or transport"),
        ("package", SiIconCategory.Logistics, "Package or box"),
        ("shopping-cart", SiIconCategory.Commerce, "Shopping cart"),
        ("credit-card", SiIconCategory.Commerce, "Payment card"),
        ("wallet", SiIconCategory.Commerce, "Wallet or balance"),
        ("filter", SiIconCategory.Actions, "Filter results"),
        ("sort", SiIconCategory.Actions, "Sort items"),
        ("sort-asc", SiIconCategory.Actions, "Sort ascending"),
        ("sort-desc", SiIconCategory.Actions, "Sort descending"),
        ("sort-none", SiIconCategory.Actions, "No sorting state"),
        ("more-vertical", SiIconCategory.Actions, "More options vertical"),
        ("more-horizontal", SiIconCategory.Actions, "More options horizontal"),
        ("maximize", SiIconCategory.Layout, "Expand to full size"),
        ("minimize", SiIconCategory.Layout, "Minimize window"),
        ("columns", SiIconCategory.Layout, "Column layout"),
        ("grid", SiIconCategory.Layout, "Grid layout"),
        ("list", SiIconCategory.Layout, "List layout"),
        ("layout", SiIconCategory.Layout, "Page or panel layout"),
        ("layout-sidebar-left", SiIconCategory.Layout, "Sidebar on the left"),
        ("layout-sidebar-right", SiIconCategory.Layout, "Sidebar on the right"),
        ("align-start", SiIconCategory.Layout, "Align content to start"),
        ("align-end", SiIconCategory.Layout, "Align content to end"),
        ("align-stretch", SiIconCategory.Layout, "Stretch content to fill"),
        ("align-space-between", SiIconCategory.Layout, "Distribute with space between"),
        ("align-distribute", SiIconCategory.Layout, "Distribute with space around"),
        ("align-left", SiIconCategory.Typography, "Align text left"),
        ("align-center", SiIconCategory.Typography, "Align text center"),
        ("align-right", SiIconCategory.Typography, "Align text right"),
        ("align-justify", SiIconCategory.Typography, "Justify text"),
        ("bold", SiIconCategory.Typography, "Bold text style"),
        ("italic", SiIconCategory.Typography, "Italic text style"),
        ("underline", SiIconCategory.Typography, "Underline text"),
        ("link", SiIconCategory.Communication, "Link or attach URL"),
        ("external-link", SiIconCategory.Communication, "Open external link"),
        ("paperclip", SiIconCategory.Communication, "Attachment"),
        ("share", SiIconCategory.Communication, "Share item"),
        ("reply", SiIconCategory.Communication, "Reply to message"),
        ("forward", SiIconCategory.Communication, "Forward message"),
        ("inbox", SiIconCategory.Communication, "Inbox tray"),
        ("outbox", SiIconCategory.Communication, "Outbox tray"),
        ("archive", SiIconCategory.Files, "Archive storage"),
        ("bookmark", SiIconCategory.Files, "Bookmark or save"),
        ("tag", SiIconCategory.Files, "Tag or label"),
        ("flag", SiIconCategory.Files, "Flag or mark"),
        ("star", SiIconCategory.Feedback, "Favorite or star"),
        ("heart", SiIconCategory.Feedback, "Like or favorite"),
        ("thumbs-up", SiIconCategory.Feedback, "Approve or like"),
        ("thumbs-down", SiIconCategory.Feedback, "Disapprove"),
        ("message-square", SiIconCategory.Communication, "Message bubble square"),
        ("message-circle", SiIconCategory.Communication, "Message bubble round"),
        ("chat-dots", SiIconCategory.Communication, "Chat with typing indicator"),
        ("help-circle", SiIconCategory.System, "Help or support"),
        ("life-buoy", SiIconCategory.System, "Support lifebuoy"),
        ("clipboard-check", SiIconCategory.Actions, "Checklist completed"),
        ("clipboard-list", SiIconCategory.Actions, "Checklist items"),
        ("form", SiIconCategory.Actions, "SufiForms — form definitions, surveys, and fillable fields"),
        ("calendar-check", SiIconCategory.Time, "Calendar with check"),
        ("calendar-x", SiIconCategory.Time, "Calendar with cancel"),
        ("repeat", SiIconCategory.Time, "Repeat or loop"),
        ("undo", SiIconCategory.Actions, "Undo action"),
        ("redo", SiIconCategory.Actions, "Redo action"),
        ("printer", SiIconCategory.Devices, "Print document"),
        ("scanner", SiIconCategory.Devices, "Scan document"),
        ("qr-code", SiIconCategory.Devices, "QR code"),
        ("barcode", SiIconCategory.Devices, "Barcode"),
        ("monitor", SiIconCategory.Devices, "Desktop monitor"),
        ("laptop", SiIconCategory.Devices, "Laptop device"),
        ("tablet", SiIconCategory.Devices, "Tablet device"),
        ("smartphone", SiIconCategory.Devices, "Mobile phone"),
        ("wifi", SiIconCategory.Devices, "Wi-Fi signal"),
        ("bluetooth", SiIconCategory.Devices, "Bluetooth connection"),
        ("battery", SiIconCategory.Devices, "Battery level"),
        ("battery-charging", SiIconCategory.Devices, "Charging battery"),
        ("plug", SiIconCategory.Devices, "Power plug"),
        ("power", SiIconCategory.Devices, "Power button"),
        ("database", SiIconCategory.Development, "Database storage"),
        ("server", SiIconCategory.Development, "Server rack"),
        ("cloud-upload", SiIconCategory.Files, "Upload to cloud"),
        ("cloud-download", SiIconCategory.Files, "Download from cloud"),
        ("code", SiIconCategory.Development, "Code brackets"),
        ("terminal", SiIconCategory.Development, "Terminal console"),
        ("bug", SiIconCategory.Development, "Bug or issue"),
        ("wrench", SiIconCategory.Tools, "Wrench tool"),
        ("hammer", SiIconCategory.Tools, "Hammer tool"),
        ("toolbox", SiIconCategory.Tools, "Toolbox"),
        ("rocket", SiIconCategory.Development, "Launch or deploy"),
        ("git-branch", SiIconCategory.Development, "Git branch"),
        ("git-commit", SiIconCategory.Development, "Git commit"),
        ("git-merge", SiIconCategory.Development, "Git merge"),
        ("component", SiIconCategory.Layout, "UI component block"),
        ("palette", SiIconCategory.Design, "Color palette"),
        ("brush", SiIconCategory.Design, "Brush or paint"),
        ("sparkles", SiIconCategory.Ai, "Magic or enhancement"),
        ("bot", SiIconCategory.Ai, "Bot or automation"),
        ("brain", SiIconCategory.Ai, "Intelligence or AI"),
        ("cpu", SiIconCategory.Ai, "CPU or chip"),
        ("fingerprint", SiIconCategory.Security, "Biometric fingerprint"),
        ("shield-alert", SiIconCategory.Security, "Security alert"),
        ("coins", SiIconCategory.Commerce, "Coins or tokens"),
        ("bank", SiIconCategory.Commerce, "Bank building"),
        ("receipt", SiIconCategory.Commerce, "Receipt or bill"),
        ("invoice", SiIconCategory.Commerce, "Invoice document"),
        ("percent", SiIconCategory.Commerce, "Discount percent"),
        ("ticket", SiIconCategory.Commerce, "Ticket or pass"),
        ("shopping-bag", SiIconCategory.Commerce, "Shopping bag"),
        ("cart-plus", SiIconCategory.Commerce, "Add to cart"),
        ("cart-minus", SiIconCategory.Commerce, "Remove from cart"),
        ("map-pin-off", SiIconCategory.Location, "Location disabled"),
        ("compass", SiIconCategory.Location, "Compass navigation"),
        ("route", SiIconCategory.Location, "Route path"),
        ("car", SiIconCategory.Logistics, "Car transport"),
        ("plane", SiIconCategory.Logistics, "Air travel"),
        ("ship", SiIconCategory.Logistics, "Sea transport"),
        ("apps-down", SiIconCategory.System, "Apps pointing down."),
        ("tag-square", SiIconCategory.Commerce, "Tag with square modifier."),
        ("user-x-plus", SiIconCategory.Users, "User X with plus modifier."),
        ("receipt-up", SiIconCategory.Commerce, "Receipt pointing up."),
        ("file-square", SiIconCategory.Files, "File with square modifier."),
        ("wifi-badge", SiIconCategory.Devices, "Wifi with badge modifier."),
        ("shield-user-alt", SiIconCategory.Users, "Shield User with alt modifier."),
        ("edit-down", SiIconCategory.Actions, "Edit pointing down."),
        ("repeat-left", SiIconCategory.Time, "Repeat pointing left."),
        ("export-square", SiIconCategory.Data, "Export with square modifier."),
        ("vector-circle", SiIconCategory.Ai, "Vector with circle modifier."),
        ("bookmark-right", SiIconCategory.Files, "Bookmark pointing right."),
        ("usb-up", SiIconCategory.Devices, "Usb pointing up."),
        ("heart-square", SiIconCategory.Health, "Heart with square modifier."),
        ("bell-circle", SiIconCategory.System, "Bell with circle modifier."),
        ("vault-right", SiIconCategory.Security, "Vault pointing right."),
        ("plane-badge", SiIconCategory.Travel, "Plane with badge modifier."),
        ("table-down", SiIconCategory.Data, "Table pointing down."),
        ("safe-up", SiIconCategory.Security, "Safe pointing up."),
        ("mail-square", SiIconCategory.Communication, "Mail with square modifier."),
        ("api-circle", SiIconCategory.Data, "Api with circle modifier."),
        ("hotel-right", SiIconCategory.Travel, "Hotel pointing right."),
        ("schedule-alt", SiIconCategory.Time, "Schedule with alt modifier."),
        ("download-left", SiIconCategory.Actions, "Download pointing left."),
        ("rss-plus", SiIconCategory.Communication, "Rss with plus modifier."),
        ("barcode-circle", SiIconCategory.Commerce, "Barcode with circle modifier."),
        ("assistant-alt", SiIconCategory.Ai, "Assistant with alt modifier."),
        ("globe-plus", SiIconCategory.Location, "Globe with plus modifier."),
        ("comment-down", SiIconCategory.Communication, "Comment pointing down."),
        ("database-circle", SiIconCategory.Development, "Database with circle modifier."),
        ("schema-alt", SiIconCategory.Data, "Schema with alt modifier."),
        ("folder-x", SiIconCategory.Files, "Folder with x modifier."),
        ("swap-down", SiIconCategory.Navigation, "Swap pointing down."),
        ("dashboard-alt", SiIconCategory.System, "Dashboard with alt modifier."),
        ("pill-slash", SiIconCategory.Health, "Pill with slash modifier."),
        ("dna-right", SiIconCategory.Health, "Dna pointing right."),
        ("suitcase-check", SiIconCategory.Travel, "Suitcase with check modifier."),
        ("hotel-alt", SiIconCategory.Travel, "Hotel with alt modifier."),
        ("api-right", SiIconCategory.Data, "Api pointing right."),
        ("plugin-square", SiIconCategory.System, "Plugin with square modifier."),
        ("firewall-circle", SiIconCategory.Security, "Firewall with circle modifier."),
        ("qr-plus", SiIconCategory.Commerce, "Qr with plus modifier."),
        ("playlist-up", SiIconCategory.Media, "Playlist pointing up."),
        ("waveform-alt", SiIconCategory.Media, "Waveform with alt modifier."),
        ("vector-up", SiIconCategory.Ai, "Vector pointing up."),
        ("embedding-square", SiIconCategory.Ai, "Embedding with square modifier."),
        ("mention-left", SiIconCategory.Communication, "Mention pointing left."),
        ("broadcast-circle", SiIconCategory.Communication, "Broadcast with circle modifier."),
        ("signal-alt", SiIconCategory.Communication, "Signal with alt modifier."),
        ("export-plus", SiIconCategory.Data, "Export with plus modifier."),
        ("import-plus", SiIconCategory.Data, "Import with plus modifier."),
        ("pipeline-down", SiIconCategory.Data, "Pipeline pointing down."),
        ("graph-circle", SiIconCategory.Data, "Graph with circle modifier."),
        ("node-plus", SiIconCategory.Data, "Node with plus modifier."),
        ("link-alt", SiIconCategory.Data, "Link with alt modifier."),
        ("assistant-right", SiIconCategory.Ai, "Assistant pointing right."),
        ("prompt-square", SiIconCategory.Ai, "Prompt with square modifier."),
        ("model-plus", SiIconCategory.Ai, "Model with plus modifier."),
        ("chip-ai-alt", SiIconCategory.Ai, "Chip Ai with alt modifier."),
        ("dataset-circle", SiIconCategory.Ai, "Dataset with circle modifier."),
        ("auto-right", SiIconCategory.Ai, "Auto pointing right."),
        ("magic-wand-left", SiIconCategory.Ai, "Magic Wand pointing left."),
        ("spark-badge", SiIconCategory.Ai, "Spark with badge modifier."),
        ("stars-up", SiIconCategory.Ai, "Stars pointing up."),
        ("vector-badge", SiIconCategory.Ai, "Vector with badge modifier."),
        ("embedding-circle", SiIconCategory.Ai, "Embedding with circle modifier."),
        ("model-alt", SiIconCategory.Ai, "Model with alt modifier."),
        ("prompt-right", SiIconCategory.Ai, "Prompt pointing right."),
        ("bot-plus", SiIconCategory.Ai, "Bot with plus modifier."),
        ("brain-circle", SiIconCategory.Ai, "Brain with circle modifier."),
        ("neural-net-square", SiIconCategory.Ai, "Neural Net with square modifier."),
        ("chip-ai-square", SiIconCategory.Ai, "Chip Ai with square modifier."),
        ("embedding-up", SiIconCategory.Ai, "Embedding pointing up."),
        ("vector-right", SiIconCategory.Ai, "Vector pointing right."),
        ("model-circle", SiIconCategory.Ai, "Model with circle modifier."),
        ("assistant-plus", SiIconCategory.Ai, "Assistant with plus modifier."),
        ("auto-circle", SiIconCategory.Ai, "Auto with circle modifier."),
        ("dataset-alt", SiIconCategory.Ai, "Dataset with alt modifier."),
        ("spark-right", SiIconCategory.Ai, "Spark pointing right."),
        ("magic-wand-alt", SiIconCategory.Ai, "Magic Wand with alt modifier."),
        ("stars-circle", SiIconCategory.Ai, "Stars with circle modifier."),
        ("prompt-circle", SiIconCategory.Ai, "Prompt with circle modifier."),
        ("assistant-circle", SiIconCategory.Ai, "Assistant with circle modifier."),
        ("auto-alt", SiIconCategory.Ai, "Auto with alt modifier."),
        ("dataset-right", SiIconCategory.Ai, "Dataset pointing right."),
        ("chip-ai-circle", SiIconCategory.Ai, "Chip Ai with circle modifier."),
        ("embedding-badge", SiIconCategory.Ai, "Embedding with badge modifier."),
        ("vector-square", SiIconCategory.Ai, "Vector with square modifier."),
        ("model-right", SiIconCategory.Ai, "Model pointing right."),
        ("assistant-up", SiIconCategory.Ai, "Assistant pointing up."),
        ("auto-up", SiIconCategory.Ai, "Auto pointing up."),
        ("dataset-up", SiIconCategory.Ai, "Dataset pointing up."),
        ("neural-net-circle", SiIconCategory.Ai, "Neural Net with circle modifier."),
        ("bot-alt", SiIconCategory.Ai, "Bot with alt modifier."),
        ("brain-square", SiIconCategory.Ai, "Brain with square modifier."),
        ("prompt-up", SiIconCategory.Ai, "Prompt pointing up."),
        ("magic-wand-up", SiIconCategory.Ai, "Magic Wand pointing up."),
        ("spark-circle", SiIconCategory.Ai, "Spark with circle modifier."),
        ("stars-square", SiIconCategory.Ai, "Stars with square modifier."),
        ("assistant-square", SiIconCategory.Ai, "Assistant with square modifier."),
        ("auto-square", SiIconCategory.Ai, "Auto with square modifier."),
        ("dataset-square", SiIconCategory.Ai, "Dataset with square modifier."),
        ("chip-ai-up", SiIconCategory.Ai, "Chip Ai pointing up."),
        ("embedding-alt", SiIconCategory.Ai, "Embedding with alt modifier."),
        ("vector-alt", SiIconCategory.Ai, "Vector with alt modifier."),
        ("model-square", SiIconCategory.Ai, "Model with square modifier."),
        ("assistant-badge", SiIconCategory.Ai, "Assistant with badge modifier."),
        ("auto-badge", SiIconCategory.Ai, "Auto with badge modifier."),
        ("dataset-badge", SiIconCategory.Ai, "Dataset with badge modifier."),
        ("chip-ai-badge", SiIconCategory.Ai, "Chip Ai with badge modifier."),
        ("embedding-right", SiIconCategory.Ai, "Embedding pointing right."),
        ("vector-down", SiIconCategory.Ai, "Vector pointing down."),
        ("model-down", SiIconCategory.Ai, "Model pointing down."),
        ("assistant-down", SiIconCategory.Ai, "Assistant pointing down."),
        ("auto-down", SiIconCategory.Ai, "Auto pointing down."),
        ("dataset-down", SiIconCategory.Ai, "Dataset pointing down."),
        ("chip-ai-down", SiIconCategory.Ai, "Chip Ai pointing down."),
        ("embedding-down", SiIconCategory.Ai, "Embedding pointing down."),
        ("prompt-down", SiIconCategory.Ai, "Prompt pointing down."),
        ("magic-wand-down", SiIconCategory.Ai, "Magic Wand pointing down."),
        ("spark-down", SiIconCategory.Ai, "Spark pointing down."),
        ("stars-down", SiIconCategory.Ai, "Stars pointing down."),
        ("privacy-check", SiIconCategory.Security, "Privacy with check modifier."),
        ("archive-square", SiIconCategory.Files, "Archive with square modifier."),
        ("calendar-up", SiIconCategory.Time, "Calendar pointing up."),
        ("thermometer-x", SiIconCategory.Health, "Thermometer with x modifier."),
        ("bug-circle", SiIconCategory.Development, "Bug with circle modifier."),
        ("plane-left", SiIconCategory.Travel, "Plane pointing left."),
        ("route-badge", SiIconCategory.Location, "Route with badge modifier."),
        ("database-right", SiIconCategory.Development, "Database pointing right."),
        ("ticket-square", SiIconCategory.Commerce, "Ticket with square modifier."),
        ("stethoscope-alt", SiIconCategory.Health, "Stethoscope with alt modifier."),
        ("vault-badge", SiIconCategory.Security, "Vault with badge modifier."),
        ("apps-right", SiIconCategory.System, "Apps pointing right."),
        ("map-square", SiIconCategory.Location, "Map with square modifier."),
        ("hotel-square", SiIconCategory.Travel, "Hotel with square modifier."),
        ("folder-check", SiIconCategory.Files, "Folder with check modifier."),
        ("file-badge", SiIconCategory.Files, "File with badge modifier."),
        ("certificate-circle", SiIconCategory.Security, "Certificate with circle modifier."),
        ("2fa-square", SiIconCategory.Security, "2Fa with square modifier."),
        ("scan-alt", SiIconCategory.Security, "Scan with alt modifier."),
        ("safe-circle", SiIconCategory.Security, "Safe with circle modifier."),
        ("firewall-right", SiIconCategory.Security, "Firewall pointing right."),
        ("lock-circle", SiIconCategory.Security, "Lock with circle modifier."),
        ("unlock-badge", SiIconCategory.Security, "Unlock with badge modifier."),
        ("key-square", SiIconCategory.Security, "Key with square modifier."),
        ("shield-square", SiIconCategory.Security, "Shield with square modifier."),
        ("fingerprint-circle", SiIconCategory.Security, "Fingerprint with circle modifier."),
        ("privacy-alt", SiIconCategory.Security, "Privacy with alt modifier."),
        ("certificate-square", SiIconCategory.Security, "Certificate with square modifier."),
        ("vault-square", SiIconCategory.Security, "Vault with square modifier."),
        ("firewall-square", SiIconCategory.Security, "Firewall with square modifier."),
        ("safe-square", SiIconCategory.Security, "Safe with square modifier."),
        ("scan-square", SiIconCategory.Security, "Scan with square modifier."),
        ("2fa-circle", SiIconCategory.Security, "2Fa with circle modifier."),
        ("privacy-circle", SiIconCategory.Security, "Privacy with circle modifier."),
        ("certificate-badge", SiIconCategory.Security, "Certificate with badge modifier."),
        ("vault-circle", SiIconCategory.Security, "Vault with circle modifier."),
        ("safe-badge", SiIconCategory.Security, "Safe with badge modifier."),
        ("scan-circle", SiIconCategory.Security, "Scan with circle modifier."),
        ("2fa-badge", SiIconCategory.Security, "2Fa with badge modifier."),
        ("privacy-square", SiIconCategory.Security, "Privacy with square modifier."),
        ("certificate-alt", SiIconCategory.Security, "Certificate with alt modifier."),
        ("vault-alt", SiIconCategory.Security, "Vault with alt modifier."),
        ("firewall-alt", SiIconCategory.Security, "Firewall with alt modifier."),
        ("safe-alt", SiIconCategory.Security, "Safe with alt modifier."),
        ("scan-badge", SiIconCategory.Security, "Scan with badge modifier."),
        ("2fa-alt", SiIconCategory.Security, "2Fa with alt modifier."),
        ("privacy-badge", SiIconCategory.Security, "Privacy with badge modifier."),
        ("certificate-right", SiIconCategory.Security, "Certificate pointing right."),
        ("safe-right", SiIconCategory.Security, "Safe pointing right."),
        ("scan-right", SiIconCategory.Security, "Scan pointing right."),
        ("2fa-right", SiIconCategory.Security, "2Fa pointing right."),
        ("privacy-right", SiIconCategory.Security, "Privacy pointing right."),
        ("certificate-up", SiIconCategory.Security, "Certificate pointing up."),
        ("vault-up", SiIconCategory.Security, "Vault pointing up."),
        ("firewall-up", SiIconCategory.Security, "Firewall pointing up."),
        ("scan-up", SiIconCategory.Security, "Scan pointing up."),
        ("2fa-up", SiIconCategory.Security, "2Fa pointing up."),
        ("privacy-up", SiIconCategory.Security, "Privacy pointing up."),
        ("archive-circle", SiIconCategory.Files, "Archive with circle modifier."),
        ("archive-badge", SiIconCategory.Files, "Archive with badge modifier."),
        ("archive-alt", SiIconCategory.Files, "Archive with alt modifier."),
        ("archive-right", SiIconCategory.Files, "Archive pointing right."),
        ("archive-up", SiIconCategory.Files, "Archive pointing up."),
        ("archive-down", SiIconCategory.Files, "Archive pointing down."),
        ("calendar-right", SiIconCategory.Time, "Calendar pointing right."),
        ("calendar-circle", SiIconCategory.Time, "Calendar with circle modifier."),
        ("calendar-square", SiIconCategory.Time, "Calendar with square modifier."),
        ("calendar-badge", SiIconCategory.Time, "Calendar with badge modifier."),
        ("calendar-alt", SiIconCategory.Time, "Calendar with alt modifier."),
        ("calendar-down", SiIconCategory.Time, "Calendar pointing down."),
        ("thermometer-circle", SiIconCategory.Health, "Thermometer with circle modifier."),
        ("thermometer-square", SiIconCategory.Health, "Thermometer with square modifier."),
        ("thermometer-badge", SiIconCategory.Health, "Thermometer with badge modifier."),
        ("thermometer-alt", SiIconCategory.Health, "Thermometer with alt modifier."),
        ("thermometer-right", SiIconCategory.Health, "Thermometer pointing right."),
        ("thermometer-up", SiIconCategory.Health, "Thermometer pointing up."),
        ("thermometer-down", SiIconCategory.Health, "Thermometer pointing down."),
        ("bug-square", SiIconCategory.Development, "Bug with square modifier."),
        ("bug-badge", SiIconCategory.Development, "Bug with badge modifier."),
        ("bug-alt", SiIconCategory.Development, "Bug with alt modifier."),
        ("bug-right", SiIconCategory.Development, "Bug pointing right."),
        ("bug-up", SiIconCategory.Development, "Bug pointing up."),
        ("bug-down", SiIconCategory.Development, "Bug pointing down."),
        ("plane-circle", SiIconCategory.Travel, "Plane with circle modifier."),
        ("plane-square", SiIconCategory.Travel, "Plane with square modifier."),
        ("plane-alt", SiIconCategory.Travel, "Plane with alt modifier."),
        ("plane-right", SiIconCategory.Travel, "Plane pointing right."),
        ("plane-up", SiIconCategory.Travel, "Plane pointing up."),
        ("plane-down", SiIconCategory.Travel, "Plane pointing down."),
        ("route-circle", SiIconCategory.Location, "Route with circle modifier."),
        ("route-square", SiIconCategory.Location, "Route with square modifier."),
        ("route-alt", SiIconCategory.Location, "Route with alt modifier."),
        ("route-right", SiIconCategory.Location, "Route pointing right."),
        ("route-up", SiIconCategory.Location, "Route pointing up."),
        ("route-down", SiIconCategory.Location, "Route pointing down."),
        ("database-up", SiIconCategory.Development, "Database pointing up."),
        ("database-down", SiIconCategory.Development, "Database pointing down."),
        ("database-square", SiIconCategory.Development, "Database with square modifier."),
        ("database-badge", SiIconCategory.Development, "Database with badge modifier."),
        ("database-alt", SiIconCategory.Development, "Database with alt modifier."),
        ("ticket-circle", SiIconCategory.Commerce, "Ticket with circle modifier."),
        ("ticket-badge", SiIconCategory.Commerce, "Ticket with badge modifier."),
        ("ticket-alt", SiIconCategory.Commerce, "Ticket with alt modifier."),
        ("ticket-right", SiIconCategory.Commerce, "Ticket pointing right."),
        ("ticket-up", SiIconCategory.Commerce, "Ticket pointing up."),
        ("ticket-down", SiIconCategory.Commerce, "Ticket pointing down."),
        ("stethoscope-circle", SiIconCategory.Health, "Stethoscope with circle modifier."),
        ("stethoscope-square", SiIconCategory.Health, "Stethoscope with square modifier."),
        ("stethoscope-badge", SiIconCategory.Health, "Stethoscope with badge modifier."),
        ("stethoscope-right", SiIconCategory.Health, "Stethoscope pointing right."),
        ("stethoscope-up", SiIconCategory.Health, "Stethoscope pointing up."),
        ("stethoscope-down", SiIconCategory.Health, "Stethoscope pointing down."),
        ("hotel", SiIconCategory.Travel, "Hotel icon for travel UI."),
        ("tour", SiIconCategory.Travel, "Tour icon for travel UI."),
        ("archive-minus", SiIconCategory.Files, "Archive with minus modifier."),
        ("archive-plus", SiIconCategory.Files, "Archive with plus modifier."),
        ("archive-check", SiIconCategory.Files, "Archive with check modifier."),
        ("archive-x", SiIconCategory.Files, "Archive with x modifier."),
        ("stopwatch", SiIconCategory.Time, "Stopwatch icon for time UI."),
        ("schedule", SiIconCategory.Time, "Schedule icon for time UI."),
        ("history", SiIconCategory.Time, "History icon for time UI."),
        ("deadline", SiIconCategory.Time, "Deadline icon for time UI."),
        ("calendar-plus", SiIconCategory.Time, "Calendar with plus modifier."),
        ("calendar-minus", SiIconCategory.Time, "Calendar with minus modifier."),
        ("clock-plus", SiIconCategory.Time, "Clock with plus modifier."),
        ("clock-minus", SiIconCategory.Time, "Clock with minus modifier."),
        ("clock-check", SiIconCategory.Time, "Clock with check modifier."),
        ("clock-x", SiIconCategory.Time, "Clock with x modifier."),
        ("timer-plus", SiIconCategory.Time, "Timer with plus modifier."),
        ("timer-minus", SiIconCategory.Time, "Timer with minus modifier."),
        ("timer-check", SiIconCategory.Time, "Timer with check modifier."),
        ("timer-x", SiIconCategory.Time, "Timer with x modifier."),
        ("stopwatch-plus", SiIconCategory.Time, "Stopwatch with plus modifier."),
        ("stopwatch-minus", SiIconCategory.Time, "Stopwatch with minus modifier."),
        ("stopwatch-check", SiIconCategory.Time, "Stopwatch with check modifier."),
        ("stopwatch-x", SiIconCategory.Time, "Stopwatch with x modifier."),
        ("schedule-plus", SiIconCategory.Time, "Schedule with plus modifier."),
        ("schedule-minus", SiIconCategory.Time, "Schedule with minus modifier."),
        ("schedule-check", SiIconCategory.Time, "Schedule with check modifier."),
        ("schedule-x", SiIconCategory.Time, "Schedule with x modifier."),
        ("history-plus", SiIconCategory.Time, "History with plus modifier."),
        ("history-minus", SiIconCategory.Time, "History with minus modifier."),
        ("history-check", SiIconCategory.Time, "History with check modifier."),
        ("history-x", SiIconCategory.Time, "History with x modifier."),
        ("deadline-plus", SiIconCategory.Time, "Deadline with plus modifier."),
        ("deadline-minus", SiIconCategory.Time, "Deadline with minus modifier."),
        ("deadline-check", SiIconCategory.Time, "Deadline with check modifier."),
        ("deadline-x", SiIconCategory.Time, "Deadline with x modifier."),
        ("repeat-plus", SiIconCategory.Time, "Repeat with plus modifier."),
        ("repeat-minus", SiIconCategory.Time, "Repeat with minus modifier."),
        ("repeat-check", SiIconCategory.Time, "Repeat with check modifier."),
        ("repeat-x", SiIconCategory.Time, "Repeat with x modifier."),
        ("tour-alt", SiIconCategory.Travel, "Tour with alt modifier."),
        ("tour-circle", SiIconCategory.Travel, "Tour with circle modifier."),
        ("tour-square", SiIconCategory.Travel, "Tour with square modifier."),
        ("tour-badge", SiIconCategory.Travel, "Tour with badge modifier."),
        ("hotel-circle", SiIconCategory.Travel, "Hotel with circle modifier."),
        ("hotel-badge", SiIconCategory.Travel, "Hotel with badge modifier."),
        ("tour-right", SiIconCategory.Travel, "Tour pointing right."),
        ("tour-up", SiIconCategory.Travel, "Tour pointing up."),
        ("tour-down", SiIconCategory.Travel, "Tour pointing down."),
        ("hotel-up", SiIconCategory.Travel, "Hotel pointing up."),
        ("hotel-down", SiIconCategory.Travel, "Hotel pointing down."),
        ("tour-left", SiIconCategory.Travel, "Tour pointing left."),
        ("hotel-left", SiIconCategory.Travel, "Hotel pointing left."),
        ("tour-plus", SiIconCategory.Travel, "Tour with plus modifier."),
        ("tour-minus", SiIconCategory.Travel, "Tour with minus modifier."),
        ("tour-check", SiIconCategory.Travel, "Tour with check modifier."),
        ("tour-x", SiIconCategory.Travel, "Tour with x modifier."),
        ("hotel-plus", SiIconCategory.Travel, "Hotel with plus modifier."),
        ("hotel-minus", SiIconCategory.Travel, "Hotel with minus modifier."),
        ("hotel-check", SiIconCategory.Travel, "Hotel with check modifier."),
        ("hotel-x", SiIconCategory.Travel, "Hotel with x modifier."),
    ];
}