import { execSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const frontendDir = resolve(import.meta.dirname, "..");
const rclWwwroot = resolve(frontendDir, "../src/SufiChain.SufiBlazor/wwwroot");
const outDir = resolve(rclWwwroot, "_sufi/editors");
const hostCssPath = resolve(rclWwwroot, "sufiblazor-editors.css");
const chromeCssPath = resolve(frontendDir, "src/chrome.css");

execSync("npm run build", { cwd: frontendDir, stdio: "inherit" });

const required = [
  "rich-text/index.js",
  "code/index.js",
  "diff/index.js",
  "viewer/index.js",
];

const missing = required.filter((file) => !existsSync(resolve(outDir, file)));
if (missing.length > 0) {
  console.error("Editor bundle check failed. Missing:", missing.join(", "));
  process.exit(1);
}

const stylesDir = resolve(outDir, "styles");
const styleFiles = existsSync(stylesDir)
  ? readdirSync(stylesDir).filter((name) => name.endsWith(".css")).sort()
  : [];

const parts = [
  "/* Generated by frontend/scripts/check.mjs. Do not edit by hand. */",
  "",
];

if (existsSync(chromeCssPath)) {
  parts.push("/* chrome */", readFileSync(chromeCssPath, "utf8").trim(), "");
}

for (const file of styleFiles) {
  parts.push(`/* ${file} */`, readFileSync(resolve(stylesDir, file), "utf8").trim(), "");
}

writeFileSync(hostCssPath, `${parts.join("\n").trim()}\n`);

if (!existsSync(hostCssPath)) {
  console.error("Editor bundle check failed. Missing host CSS:", hostCssPath);
  process.exit(1);
}

console.log("Editor bundle check passed.");
console.log("Wrote", hostCssPath);
